language: ruby
rvm:
  - 2.4
before_script:
  - bundle install
  - bundle exec puppet --version
matrix:
  include:
  - name: "Puppet 5"
    rvm: "2.4"
    env: PUPPET_GEM_VERSION='~> 5.0'
  - name: "Puppet 6"
    rvm: "2.5"
    env: PUPPET_GEM_VERSION='~> 6.0'
  - name: "Puppet 7"
    rvm: "2.7"
    env: PUPPET_GEM_VERSION='~> 7.0'
gemfile: Gemfile
notifications:
  email: false
